
-- User Table

DROP TABLE IF EXISTS TBL_USER CASCADE;
/
DROP SEQUENCE IF EXISTS SEQ_USER;
/

CREATE SEQUENCE SEQ_USER START 101;
/
CREATE TABLE IF NOT EXISTS TBL_USER (
	ID INTEGER CONSTRAINT PK_USER_ID PRIMARY KEY DEFAULT NEXTVAL('SEQ_USER'),
	NAME VARCHAR(200) NOT NULL,
	USER_NAME VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	DOB DATE,
	PROFILE_IMAGE_ID INTEGER,
	PROFILE_IMAGE_NAME VARCHAR(200),
	CONSTRAINT UK_USER_USERNAME UNIQUE(USER_NAME)
);
/

DROP TABLE IF EXISTS TBL_TASK CASCADE;
/

DROP SEQUENCE IF EXISTS SEQ_TASK;
/

CREATE SEQUENCE SEQ_TASK START 101;
/

CREATE TABLE IF NOT EXISTS TBL_TASK (
	ID INTEGER CONSTRAINT PK_TASK_ID PRIMARY KEY DEFAULT NEXTVAL('SEQ_TASK'),
	NAME VARCHAR(500) NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	PRIORITY INTEGER DEFAULT 0 NOT NULL ,
	CREATED_USER_ID INT NOT NULL,
	CREATED_DATE DATE DEFAULT current_date,
	ASSIGNEE_USER_ID INT,
	COMPLETED_DATE DATE,
	COMMENTS VARCHAR(2000),
	constraint FK_TASK_CREATOR foreign key (CREATED_USER_ID) references TBL_USER(ID),
	constraint FK_TASK_ASSIGNEE foreign key (ASSIGNEE_USER_ID) references TBL_USER(ID)
);

/
